### ISSUE TITLE
3d object static zoom

### ISSUE THREAD

**Issue by AlexandreRangel** [cvalenzuela/Mappa#12]
Dear friends from Mappa,

is this the right place for code questions?

I'm building a project based on the three.js + mapbox example (https://mappa.js.org/docs/examples-three-js.html) but I'd like to have a different 3d object zoom behaviour.
I'd like the 3d objects on top of the map to change the zoom level according to the map zoom, so they could keep their relative sizes to the map features. Is it possible?

Thank you!

Alexandre Rangel
www.quasecinema.org

**Comment by cvalenzuela** [comment]
yes, it is totally possible.
You can use the `zoom()` function: https://mappa.js.org/docs/api-zoom.html

**Comment by cvalenzuela** [comment]
closing this for now as it seems resolved. feel free to reopen if necessary
