### ISSUE TITLE
Can't remove zoomControls with Leaflet map

### ISSUE THREAD

**Issue by aarondruck** [cvalenzuela/Mappa#20]
Hi there

I can't seem to remove the Leaflet map zoomControls, stop zooming on mouseScroll, or the Leaflet watermark.

I added zoomControl:false to options {}, but that didn't seem to work.

<img width="466" alt="screen shot 2018-06-05 at 6 45 03 am" src="https://user-images.githubusercontent.com/2692810/40979920-0436f8ca-688c-11e8-8922-202676e353b0.png">

Any ideas?

**Comment by cvalenzuela** [comment]
You should be able to remove the `zoomControls` like this:

```javascript
var myMap = mappa.tileMap();
myMap.map.zoomControl.remove()
```

**Comment by aarondruck** [comment]
Thanks for the help!
