### ISSUE TITLE
package.json "main" incorrect?

### ISSUE THREAD

**Issue by allonhadaya** [cvalenzuela/Mappa#3]
Hey, what a cool project! I'm really excited to play with it.

package.json:
```js
{
    ...
    "main": "dist/index.js",
    ...
}
```

but it looks like that file does not exist
```sh
> ls node_modules/mappa-mundi/dist
mappa.js  mappa.js.map  mappa.min.js  mappa.min.js.map
```

Should main be pointing to mappa.js instead, or should an index.js file actually exist?

**Comment by cvalenzuela** [comment]
nice catch! yes, it should point to mappa.js
I'll fix it right away.

Please try it and feel free to submit PR or send me your feedback!

**Comment by allonhadaya** [comment]
It looks like it's working now. Thanks!
